dist: xenial
language: python
python:
  - "3.7.5"
  
services:
  - docker

cache:
  apt: true
  pip: true
  yarn: true
  directories:
    - $HOME/download-cache

before_install:
  - mkdir -p $HOME/download-cache
  - docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  
install:
  - pip3 install -r requirements.txt
  - docker ps -a
